### ISSUE TITLE
Parameters Added with \Cmp\Http\Message\Request::withQueryParameter are not always encoded

### ISSUE THREAD

**Issue by skyellin** [CMProductions/http-client#16]
The issue seems to be that previously encoded parameters are decoded at Symfony/vendor/pluggit/http-client/src/Message/Request.php:81, so only the last parameter gets encoded.  

Fixing this can cause backwards compatibility issues, so I would increment the major version.

**Comment by hmoragregaCMP** [comment]
Good catch! Agree with the major version change 👍

**Comment by danielmartincmp** [comment]
A related issue was fixed by https://github.com/CMProductions/http-client/pull/14/files
Note that `parse_str`is already url decoding the params:
http://php.net/manual/es/function.parse-str.php#72745

**Comment by danielmartincmp** [comment]
We where using version 1.1.0 without this last fix: http://php.net/manual/es/function.parse-str.php#72745
We'll update to the latest.
